//read, name, image, text, message, post, link, ago, picture
export const notifications = [
  {
    read: false,
    name: "Mark Webber",
    image: "/notifications-page/avatar-mark-webber.webp",
    text: "reacted to your recent post",
    message: "",
    post: "My first tournament today! ",
    link: "",
    ago: "1m ago",
    picture: "",
  },
  {
    read: false,
    name: "Angela Gray",
    image: "/notifications-page/avatar-angela-gray.webp",
    text: "followed you",
    message: "",
    post: "",
    link: "",
    ago: "5m ago",
    picture: "",
  },
  {
    read: false,
    name: "Jacob Thompson",
    image: "/notifications-page/avatar-jacob-thompson.webp",
    text: "has joined your group",
    message: "",
    post: "",
    link: "Chess Club",
    ago: "1 day ago",
    picture: "",
  },
  {
    read: true,
    name: "Rizky Hasanuddin",
    image: "/notifications-page/avatar-rizky-hasanuddin.webp",
    text: "sent you a private message",
    message:
      "Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.",
    post: "",
    link: "",
    ago: "5 days ago",
    picture: "",
  },
  {
    read: true,
    name: "Kimberly Smith",
    image: "/notifications-page/avatar-kimberly-smith.webp",
    text: "commented on your picture",
    message: "",
    post: "",
    link: "",
    ago: "1 week ago",
    picture: "/notifications-page/image-chess.webp",
  },
  {
    read: true,
    name: "Nathan Peterson",
    image: "/notifications-page/avatar-nathan-peterson.webp",
    text: "reacted to your recent post",
    message: "",
    post: "5 end-game strategies to increase your win rate",
    link: "",
    ago: "2 weeks ago",
    picture: "",
  },
  {
    read: true,
    name: "Anna Kim",
    image: "/notifications-page/avatar-anna-kim.webp",
    text: "left the group",
    message: "",
    post: "",
    link: "Chess Club",
    ago: "2 weeks ago",
    picture: "",
  },
];
